//
// Created by Ziel on 2024/08/03.
//

#ifndef QUANTUMQUEST_GAMEACTIVITYMOTIONEVENT_H
#define QUANTUMQUEST_GAMEACTIVITYMOTIONEVENT_H


class GameActivityMotionEvent {

};


#endif //QUANTUMQUEST_GAMEACTIVITYMOTIONEVENT_H